/**
 * RedTeamOrchestrator — Phase 7: Adversarial Intelligence
 * ─────────────────────────────────────────────────────────
 * Implements the 5-step Red Team Flow:
 *
 *   1. Spotter proposes an opportunity (passed in as `opportunity`)
 *   2. Sniper creates an execution plan
 *   3. Validator tries to break the plan (adversarial probing)
 *   4. Evaluator scores robustness
 *   5. Controller updates strategy / memory persists learned patterns
 *
 * Best strategies and failed attack patterns are stored to long-term memory
 * so the agent improves over time by challenging itself.
 */

import { Sniper } from '../../modules/sniper';
import { ToolValidator } from '../../modules/validator';
import { Evaluator } from '../../modules/evaluator';
import { LLMInterface } from '../../cognition/llm';
import { MemorySystem } from '../memory';
import { AdversarialScorer, AdversarialRound, AdversarialScore } from './scorer';
import { logEvent } from '../../utils/logger';

/** Minimum robustness score (0-100) for a strategy to be persisted as "best". */
const BEST_STRATEGY_THRESHOLD = 70;

/**
 * A structured opportunity object passed to the RedTeamOrchestrator.
 * Fields beyond `id`, `tool`, and `description` are arbitrary agent-generated data.
 */
export type AgentOpportunity = {
  id?: string;
  tool?: string;
  description?: string;
  [key: string]: unknown;
};

/** A single step in a Sniper execution plan. */
export type PlanStep = {
  status: string;
  outcome?: string;
  priority?: string;
  timestamp?: string;
  action?: unknown;
  [key: string]: unknown;
};

export interface AdversarialResult {
  /** The opportunity that was evaluated. */
  opportunity: AgentOpportunity;
  /** Execution plan produced by the Sniper. */
  plan: PlanStep[];
  /** Adversarial attack vectors generated by the red-team probe. */
  attackVectors: string[];
  /** Number of attack vectors that were successfully blocked. */
  blockedAttacks: number;
  /** Composite robustness score for this round (0-100). */
  robustnessScore: number;
  /** Running adversarial metrics from the AdversarialScorer. */
  score: AdversarialScore;
  /** Human-readable description of what was stored to memory (null if nothing stored). */
  strategyUpdate: string | null;
  /**
   * Disagreement score (0–100) between the Sniper's proposed plan and the
   * Validator's adversarial challenge.  High disagreement indicates the plan is
   * contested and should be treated with elevated risk.  This creates genuine
   * multi-agent tension: the Sniper and Validator are not merely sequential —
   * they actively compete, and their disagreement is a first-class signal.
   */
  disagreementScore: number;
  /** ISO-8601 timestamp of when this round completed. */
  timestamp: string;
}

export class RedTeamOrchestrator {
  private sniper: Sniper;
  private validator: ToolValidator;
  private evaluator: Evaluator;
  private llm: LLMInterface;
  private memory: MemorySystem;
  private scorer: AdversarialScorer;

  constructor(llm: LLMInterface, memory: MemorySystem) {
    this.llm = llm;
    this.memory = memory;
    this.sniper = new Sniper();
    this.validator = new ToolValidator();
    this.evaluator = new Evaluator(llm);
    this.scorer = new AdversarialScorer();
  }

  /**
   * Runs the full 5-step adversarial cycle for the given opportunity.
   * Returns a rich result object including scores, attack vectors, and
   * what (if anything) was committed to long-term memory.
   *
   * Phase 9: The Validator now acts as a genuine adversary to the Sniper —
   * it challenges the plan with counter-arguments and produces a disagreement
   * score.  High disagreement means the plan is contested; the robustness
   * score is penalised accordingly to create real multi-agent tension.
   */
  async run(opportunity: AgentOpportunity): Promise<AdversarialResult> {
    const startTime = Date.now();
    const roundId = `rt_${startTime}`;
    const timestamp = new Date(startTime).toISOString();

    logEvent('red_team_start', { roundId, opportunity });

    // Step 2: Sniper creates execution plan
    const plan = await this.sniper.executeSurgicalStrike(opportunity);
    logEvent('red_team_plan', { roundId, planLength: plan.length });

    // Step 3: Validator tries to break the plan — adversarial probing
    const attackVectors = await this.generateAttackVectors(opportunity, plan);
    const blockedAttacks = this.countBlockedAttacks(attackVectors, plan);
    logEvent('red_team_attacks', {
      roundId,
      totalAttacks: attackVectors.length,
      blockedAttacks,
    });

    // Step 3b (Phase 9): Validator issues an explicit adversarial challenge — not
    // just a passive validity check but an active counter-argument against the
    // Sniper's plan.  The disagreement score measures how strongly the Validator
    // contests the plan (0 = full agreement, 100 = complete rejection).
    const disagreementScore = await this.scoreDisagreement(opportunity, plan, attackVectors);
    logEvent('red_team_disagreement', { roundId, disagreementScore });

    // Step 4: Evaluator scores robustness — penalised when disagreement is high.
    const robustnessScore = await this.scoreRobustness(
      plan,
      attackVectors,
      blockedAttacks,
      disagreementScore,
    );
    const executionTimeMs = Date.now() - startTime;

    // Record round in scorer for running metrics
    const round: AdversarialRound = {
      roundId,
      strategyId: opportunity.id ?? roundId,
      attacksAttempted: attackVectors.length,
      attacksBlocked: blockedAttacks,
      executionTimeMs,
      value: robustnessScore,
      timestamp,
    };
    this.scorer.record(round);
    const score = this.scorer.score();

    // Step 5: Feedback into memory
    const strategyUpdate = this.updateMemory(
      opportunity,
      plan,
      attackVectors,
      blockedAttacks,
      robustnessScore,
      score,
    );

    const result: AdversarialResult = {
      opportunity,
      plan,
      attackVectors,
      blockedAttacks,
      robustnessScore,
      score,
      strategyUpdate,
      disagreementScore,
      timestamp,
    };

    logEvent('red_team_complete', { roundId, robustnessScore, disagreementScore, score });
    return result;
  }

  // ── Private helpers ─────────────────────────────────────────────────────────

  /**
   * Asks the LLM to generate adversarial attack vectors for the given plan.
   * Falls back to a small set of simulated vectors when no LLM is available.
   */
  private async generateAttackVectors(
    opportunity: AgentOpportunity,
    plan: PlanStep[],
  ): Promise<string[]> {
    if (!this.llm.healthCheck()) {
      return this.simulateAttackVectors(opportunity);
    }

    const systemPrompt = `You are the adversarial 'Red Team' agent of RSEA.
Your goal is to find weaknesses in the proposed execution plan.
Generate realistic attack vectors or failure modes that could cause the plan to fail.
Always respond with valid JSON matching the OUTPUT PROTOCOL exactly.

OUTPUT PROTOCOL (STRICT JSON):
{
  "attacks": [
    { "vector": "description of attack", "severity": "low|medium|high" }
  ]
}`;

    const userPrompt = `OPPORTUNITY: ${JSON.stringify(opportunity)}
PLAN: ${JSON.stringify(plan).substring(0, 600)}`;

    try {
      const result = await this.llm.complete(systemPrompt, userPrompt);
      if (result?.attacks && Array.isArray(result.attacks)) {
        return (result.attacks as Array<{ vector?: string }>)
          .map((a) => (typeof a.vector === 'string' ? a.vector : String(a)))
          .filter(Boolean);
      }
    } catch {
      // fall through to simulation
    }

    return this.simulateAttackVectors(opportunity);
  }

  /** Returns a deterministic set of simulated attack vectors (used when LLM is offline). */
  private simulateAttackVectors(opportunity: AgentOpportunity): string[] {
    return [
      'Insufficient liquidity in target market',
      'Unexpected slippage during execution',
      `Invalid or missing payload for tool: ${opportunity.tool ?? 'unknown'}`,
    ];
  }

  /**
   * Counts how many attack vectors the plan's actions can withstand.
   * An attack is considered "blocked" when every step in the plan passes
   * the ToolValidator (i.e. the plan is internally valid and not trivially broken).
   */
  private countBlockedAttacks(attackVectors: string[], plan: PlanStep[]): number {
    let blocked = 0;
    for (const _vector of attackVectors) {
      const planIsValid = plan.every(step => this.validator.validate(step).valid);
      if (planIsValid) blocked++;
    }
    return blocked;
  }

  /**
   * Computes a composite robustness score (0-100).
   * 50% comes from the deterministic attack-block ratio.
   * 30% comes from the Evaluator's LLM-based opinion (falls back to 50 if LLM is offline).
   * 20% is a penalty derived from the disagreement score — high Validator disagreement
   * reduces the final robustness to reflect genuine multi-agent tension.
   */
  private async scoreRobustness(
    plan: PlanStep[],
    attackVectors: string[],
    blockedAttacks: number,
    disagreementScore: number = 0,
  ): Promise<number> {
    const baseScore =
      attackVectors.length > 0
        ? (blockedAttacks / attackVectors.length) * 100
        : 50;

    const ranked = await this.evaluator.rankStrategies(
      'Adversarial robustness assessment',
      [
        {
          id: 'red_team_plan',
          description: JSON.stringify(plan).substring(0, 200),
          status: 'pending',
        },
      ],
    );
    const llmScore = ranked[0]?.score ?? 50;

    // Disagreement penalty: 20% weight on how much the Validator contests the plan.
    // High disagreement (e.g. 80) penalises robustness by up to 16 points.
    const disagreementPenalty = (disagreementScore / 100) * 20;

    return Math.max(0, Math.round(baseScore * 0.5 + llmScore * 0.3 - disagreementPenalty));
  }

  /**
   * Scores the disagreement between the Sniper's plan and the Validator's
   * adversarial challenge (0–100: 0 = full agreement, 100 = complete rejection).
   *
   * The Validator is asked to score how strongly it contests the proposed plan.
   * Falls back to a deterministic heuristic when the LLM is offline:
   *   - If all plan steps are valid → low disagreement (20).
   *   - If any step is invalid → high disagreement (80).
   *
   * This is the core of the multi-agent tension mechanism: the Validator is not
   * a passive checker but an active adversary with its own score.
   */
  private async scoreDisagreement(
    opportunity: AgentOpportunity,
    plan: PlanStep[],
    attackVectors: string[],
  ): Promise<number> {
    if (!this.llm.healthCheck()) {
      // Deterministic fallback: plan validity as a proxy for disagreement.
      const planIsFullyValid = plan.every(step => this.validator.validate(step).valid);
      return planIsFullyValid ? 20 : 80;
    }

    const systemPrompt = `You are the adversarial 'Validator' agent of RSEA.
Your role is to challenge the Sniper's proposed execution plan — not to approve it.
Score how strongly you contest the plan from 0 (complete agreement) to 100 (complete rejection).
Consider: logical flaws, missing contingencies, exploitable weaknesses, over-confidence.
Always respond with valid JSON matching the OUTPUT PROTOCOL exactly.

OUTPUT PROTOCOL (STRICT JSON):
{
  "disagreement_score": <integer 0-100>,
  "reasons": ["...", "..."]
}`;

    const userPrompt = `OPPORTUNITY: ${JSON.stringify(opportunity)}
SNIPER PLAN: ${JSON.stringify(plan).substring(0, 400)}
KNOWN ATTACK VECTORS: ${JSON.stringify(attackVectors).substring(0, 200)}`;

    try {
      const result = await this.llm.complete(systemPrompt, userPrompt);
      const score = result?.disagreement_score;
      if (typeof score === 'number' && score >= 0 && score <= 100) {
        logEvent('red_team_validator_challenge', {
          disagreementScore: score,
          reasons: result.reasons ?? [],
        });
        return Math.round(score);
      }
    } catch {
      // fall through to heuristic
    }

    // LLM response was invalid — fall back to deterministic heuristic.
    const planIsFullyValid = plan.every(step => this.validator.validate(step).valid);
    return planIsFullyValid ? 20 : 80;
  }

  /**
   * Persists learning to long-term memory:
   *   - Stores the plan as a "best strategy" when robustness ≥ BEST_STRATEGY_THRESHOLD.
   *   - Otherwise stores the attack vectors that got through as "failed attack patterns".
   *
   * Returns a human-readable description of what was stored, or null if nothing was.
   */
  private updateMemory(
    opportunity: AgentOpportunity,
    plan: PlanStep[],
    attackVectors: string[],
    blockedAttacks: number,
    robustnessScore: number,
    score: AdversarialScore,
  ): string | null {
    const timestamp = new Date().toISOString();

    if (robustnessScore >= BEST_STRATEGY_THRESHOLD) {
      const key = `adversarial:best_strategy:${opportunity.id ?? Date.now()}`;
      this.memory.remember(
        key,
        { opportunity, plan, robustnessScore, score, timestamp },
        undefined,
        robustnessScore / 100,
      );
      logEvent('red_team_best_strategy_stored', { key, robustnessScore });
      return `Stored best strategy: ${key}`;
    }

    const failedAttacks = attackVectors.slice(
      0,
      Math.max(0, attackVectors.length - blockedAttacks),
    );
    if (failedAttacks.length > 0) {
      const key = `adversarial:failed_attack:${Date.now()}`;
      this.memory.remember(
        key,
        { attackVectors: failedAttacks, opportunity, robustnessScore, timestamp },
        undefined,
        0.8,
      );
      logEvent('red_team_failed_attack_stored', {
        key,
        failedAttackCount: failedAttacks.length,
      });
      return `Stored ${failedAttacks.length} failed attack pattern(s): ${key}`;
    }

    return null;
  }

  /** Exposes the underlying AdversarialScorer for inspection or testing. */
  getScorer(): AdversarialScorer {
    return this.scorer;
  }
}
