/**
 * RedTeamOrchestrator — Phase 7: Adversarial Intelligence
 * ─────────────────────────────────────────────────────────
 * Implements the 5-step Red Team Flow:
 *
 *   1. Spotter proposes an opportunity (passed in as `opportunity`)
 *   2. Sniper creates an execution plan
 *   3. Validator tries to break the plan (adversarial probing)
 *   4. Evaluator scores robustness
 *   5. Controller updates strategy / memory persists learned patterns
 *
 * Best strategies and failed attack patterns are stored to long-term memory
 * so the agent improves over time by challenging itself.
 */

import { Sniper } from '../../modules/sniper';
import { ToolValidator } from '../../modules/validator';
import { Evaluator } from '../../modules/evaluator';
import { LLMInterface } from '../../cognition/llm';
import { MemorySystem } from '../memory';
import { AdversarialScorer, AdversarialRound, AdversarialScore } from './scorer';
import { logEvent } from '../../utils/logger';

/** Minimum robustness score (0-100) for a strategy to be persisted as "best". */
const BEST_STRATEGY_THRESHOLD = 70;

export interface AdversarialResult {
  /** The opportunity that was evaluated. */
  opportunity: any;
  /** Execution plan produced by the Sniper. */
  plan: any[];
  /** Adversarial attack vectors generated by the red-team probe. */
  attackVectors: string[];
  /** Number of attack vectors that were successfully blocked. */
  blockedAttacks: number;
  /** Composite robustness score for this round (0-100). */
  robustnessScore: number;
  /** Running adversarial metrics from the AdversarialScorer. */
  score: AdversarialScore;
  /** Human-readable description of what was stored to memory (null if nothing stored). */
  strategyUpdate: string | null;
  /** ISO-8601 timestamp of when this round completed. */
  timestamp: string;
}

export class RedTeamOrchestrator {
  private sniper: Sniper;
  private validator: ToolValidator;
  private evaluator: Evaluator;
  private llm: LLMInterface;
  private memory: MemorySystem;
  private scorer: AdversarialScorer;

  constructor(llm: LLMInterface, memory: MemorySystem) {
    this.llm = llm;
    this.memory = memory;
    this.sniper = new Sniper();
    this.validator = new ToolValidator();
    this.evaluator = new Evaluator(llm);
    this.scorer = new AdversarialScorer();
  }

  /**
   * Runs the full 5-step adversarial cycle for the given opportunity.
   * Returns a rich result object including scores, attack vectors, and
   * what (if anything) was committed to long-term memory.
   */
  async run(opportunity: any): Promise<AdversarialResult> {
    const startTime = Date.now();
    const roundId = `rt_${startTime}`;
    const timestamp = new Date(startTime).toISOString();

    logEvent('red_team_start', { roundId, opportunity });

    // Step 2: Sniper creates execution plan
    const plan = await this.sniper.executeSurgicalStrike(opportunity);
    logEvent('red_team_plan', { roundId, planLength: plan.length });

    // Step 3: Validator tries to break the plan — adversarial probing
    const attackVectors = await this.generateAttackVectors(opportunity, plan);
    const blockedAttacks = this.countBlockedAttacks(attackVectors, plan);
    logEvent('red_team_attacks', {
      roundId,
      totalAttacks: attackVectors.length,
      blockedAttacks,
    });

    // Step 4: Evaluator scores robustness
    const robustnessScore = await this.scoreRobustness(
      plan,
      attackVectors,
      blockedAttacks,
    );
    const executionTimeMs = Date.now() - startTime;

    // Record round in scorer for running metrics
    const round: AdversarialRound = {
      roundId,
      strategyId: opportunity.id ?? roundId,
      attacksAttempted: attackVectors.length,
      attacksBlocked: blockedAttacks,
      executionTimeMs,
      value: robustnessScore,
      timestamp,
    };
    this.scorer.record(round);
    const score = this.scorer.score();

    // Step 5: Feedback into memory
    const strategyUpdate = this.updateMemory(
      opportunity,
      plan,
      attackVectors,
      blockedAttacks,
      robustnessScore,
      score,
    );

    const result: AdversarialResult = {
      opportunity,
      plan,
      attackVectors,
      blockedAttacks,
      robustnessScore,
      score,
      strategyUpdate,
      timestamp,
    };

    logEvent('red_team_complete', { roundId, robustnessScore, score });
    return result;
  }

  // ── Private helpers ─────────────────────────────────────────────────────────

  /**
   * Asks the LLM to generate adversarial attack vectors for the given plan.
   * Falls back to a small set of simulated vectors when no LLM is available.
   */
  private async generateAttackVectors(
    opportunity: any,
    plan: any[],
  ): Promise<string[]> {
    if (!this.llm.healthCheck()) {
      return this.simulateAttackVectors(opportunity);
    }

    const systemPrompt = `You are the adversarial 'Red Team' agent of RSEA.
Your goal is to find weaknesses in the proposed execution plan.
Generate realistic attack vectors or failure modes that could cause the plan to fail.
Always respond with valid JSON matching the OUTPUT PROTOCOL exactly.

OUTPUT PROTOCOL (STRICT JSON):
{
  "attacks": [
    { "vector": "description of attack", "severity": "low|medium|high" }
  ]
}`;

    const userPrompt = `OPPORTUNITY: ${JSON.stringify(opportunity)}
PLAN: ${JSON.stringify(plan).substring(0, 600)}`;

    try {
      const result = await this.llm.complete(systemPrompt, userPrompt);
      if (result?.attacks && Array.isArray(result.attacks)) {
        return result.attacks
          .map((a: any) => (typeof a.vector === 'string' ? a.vector : String(a)))
          .filter(Boolean);
      }
    } catch {
      // fall through to simulation
    }

    return this.simulateAttackVectors(opportunity);
  }

  /** Returns a deterministic set of simulated attack vectors (used when LLM is offline). */
  private simulateAttackVectors(opportunity: any): string[] {
    return [
      'Insufficient liquidity in target market',
      'Unexpected slippage during execution',
      `Invalid or missing payload for tool: ${opportunity.tool ?? 'unknown'}`,
    ];
  }

  /**
   * Counts how many attack vectors the plan's actions can withstand.
   * An attack is considered "blocked" when every step in the plan passes
   * the ToolValidator (i.e. the plan is internally valid and not trivially broken).
   */
  private countBlockedAttacks(attackVectors: string[], plan: any[]): number {
    let blocked = 0;
    for (const _vector of attackVectors) {
      const planIsValid = plan.every(step => this.validator.validate(step).valid);
      if (planIsValid) blocked++;
    }
    return blocked;
  }

  /**
   * Computes a composite robustness score (0-100).
   * 60% comes from the deterministic attack-block ratio.
   * 40% comes from the Evaluator's LLM-based opinion (falls back to 50 if LLM is offline).
   */
  private async scoreRobustness(
    plan: any[],
    attackVectors: string[],
    blockedAttacks: number,
  ): Promise<number> {
    const baseScore =
      attackVectors.length > 0
        ? (blockedAttacks / attackVectors.length) * 100
        : 50;

    const ranked = await this.evaluator.rankStrategies(
      'Adversarial robustness assessment',
      [
        {
          id: 'red_team_plan',
          description: JSON.stringify(plan).substring(0, 200),
          status: 'pending',
        },
      ],
    );
    const llmScore = ranked[0]?.score ?? 50;

    return Math.round(baseScore * 0.6 + llmScore * 0.4);
  }

  /**
   * Persists learning to long-term memory:
   *   - Stores the plan as a "best strategy" when robustness ≥ BEST_STRATEGY_THRESHOLD.
   *   - Otherwise stores the attack vectors that got through as "failed attack patterns".
   *
   * Returns a human-readable description of what was stored, or null if nothing was.
   */
  private updateMemory(
    opportunity: any,
    plan: any[],
    attackVectors: string[],
    blockedAttacks: number,
    robustnessScore: number,
    score: AdversarialScore,
  ): string | null {
    const timestamp = new Date().toISOString();

    if (robustnessScore >= BEST_STRATEGY_THRESHOLD) {
      const key = `adversarial:best_strategy:${opportunity.id ?? Date.now()}`;
      this.memory.remember(
        key,
        { opportunity, plan, robustnessScore, score, timestamp },
        undefined,
        robustnessScore / 100,
      );
      logEvent('red_team_best_strategy_stored', { key, robustnessScore });
      return `Stored best strategy: ${key}`;
    }

    const failedAttacks = attackVectors.slice(
      0,
      Math.max(0, attackVectors.length - blockedAttacks),
    );
    if (failedAttacks.length > 0) {
      const key = `adversarial:failed_attack:${Date.now()}`;
      this.memory.remember(
        key,
        { attackVectors: failedAttacks, opportunity, robustnessScore, timestamp },
        undefined,
        0.8,
      );
      logEvent('red_team_failed_attack_stored', {
        key,
        failedAttackCount: failedAttacks.length,
      });
      return `Stored ${failedAttacks.length} failed attack pattern(s): ${key}`;
    }

    return null;
  }

  /** Exposes the underlying AdversarialScorer for inspection or testing. */
  getScorer(): AdversarialScorer {
    return this.scorer;
  }
}
